[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "database-connectors"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "mysql-connector-python",
    "psycopg2-binary"
]

